//////////////
// Parametrage uchonieFilRouge
module.exports.uchronieFilRougeQr = [
	{ i: 0, q: "Sur les hauteurs des vergers d'Estival, Olivier de Serres est venu tranchmettre son expérienche et son chavoir aux pirates reconvertis en maraîchers ichi, quel est son nom de PNJ dans le temps présent?", r: "gurcanT", v:"70", url:"https://fr.wikipedia.org/wiki/Olivier_de_Serres"},
	{ i: 1, q: "Le grand couturier Yves Saint Laurent observe, depuis le Glas des Revenants et derrière son étal, les dernières tendances de la mode. Quel est son nom de PNJ dans le temps présent?", r: "wiscarD", v:"70", url:"https://fr.wikipedia.org/wiki/Yves_Saint_Laurent" },
	{ i: 2, q: "Hippocrate, le père de la médecine, a besoin dans un premier temps, de votre aide pour l'élasticité avant tout, mais ensuite il ne néglige pas les patients dont les blessures ont été recousues. Il se tient à Porta Praetoria, prêt à s'occuper de ceux qui en ont besoin. Quel est son nom de PNJ dans le temps présent?", r: "pamisoLaux", v:"70", url:"https://fr.wikipedia.org/wiki/Hippocrate" },
	{ i: 3, q: "En embarquant au quai de la Torche, on peut se rendre à un port où Jacques Cartier est aujourd'hui capitaine de la sublime Princesse de Glace, caravalle qui glisse sur les flots avec grâce et sensualité. Quel est son nom de PNJ dans le temps présent?", r: "h'rhanbolo", v:"70", url: "https://fr.wikipedia.org/wiki/Jacques_Cartier" },
	{ i: 4, q: "François Vatel prépare de la soupe un peu à l'ouest de Porta Praetoria. Quel est son nom de PNJ dans le temps présent?", r: "muniFrid", v:"70", url:"https://fr.wikipedia.org/wiki/Fran%C3%A7ois_Vatel" },
	{ i: 5, q: "Rudolf Noureev, le Seigneur de la Danse, enseigne aujourd'hui la danse du soleil à ses disciples, sur l'île Nakki, non loin d'Ok'Zundu. Quel est son nom de PNJ dans le temps présent?", r: "gona Vanu", v:"70", url:"https://fr.wikipedia.org/wiki/Rudolf_Noureev" },
	{ i: 6, q: "Giovanni Battista Belzoni est un chasseur de trésors basé à Tamamisu. Après avoir trouvé le bateau naufragé, tu peux regarder les beaux trésors qu'il a trouvés. Quel est son nom de PNJ dans le temps présent?", r: "saiKoro", v:"70", url:"https://fr.wikipedia.org/wiki/Giovanni_Battista_Belzoni" },
	{ i: 7, q: "Diogène de Sinope, le plus célèbre des Cyniques, vit à la Halte de Fesca. Fidèle à ses engagements et comme la vie coûte cher à Ul'dah, il a établi un petit campement et vivote par ses propres moyens. Quel est son nom de PNJ dans le temps présent?", r: "meMenugu", v:"70", url:"https://fr.wikipedia.org/wiki/Diog%C3%A8ne_de_Sinope" },
	{ i: 8, q: "Joseph Montgolfier est le responsable de l'installation de l'Ascenciel, quel est son nom de PNJ dans le temps présent?", r: "wyrkrHit", v:"70", url:"https://fr.wikipedia.org/wiki/Fr%C3%A8res_Montgolfier" },
	{ i: 9, q: "Charles Darwin, le père de la théorie de l'évolution, vit aujourd'hui de la chasse des créatures du désert de Sagolii. Mais fidèle à ses théories, il indique que l'on peut devenir les proies, car dans les dunes, les forrrts mangent les faibles, c'est la loi de la nature", r: "U'ndomii", v:"70", url:"https://fr.wikipedia.org/wiki/Charles_Darwin" },
	{ i: 10,q: "Si Nid-Mog est un endroit très agréable, Nicolas Copernic prefère être un peu au nord-est et en hauteur pour observer les jolies étoiles qui brillent dans le ciel. Quel est son nom de PNJ dans le temps présent?", r: "moguLe", v:"70", url:"https://fr.wikipedia.org/wiki/Nicolas_Copernic" },
	{ i: 11,q: "Bard l'archer, le tueur du dragon Smaug est maintenant stationné au nid du faucon. Il a choisi l'épée et a laissé de coté son arc. Il n'oubliera jamais la vision d'horreur de l'armée du dragon maléfique recouvrant le ciel du Coerthas. Quel est son nom de PNJ dans le temps présent?", r: "tourCenet", v:"70", url:"https://fr.wikipedia.org/wiki/Bard_(Terre_du_Milieu)" },
	{ i: 12,q: "Le confiseur Antoine Rumpelmayer propose de boire un thé avec quelques sucreries quelques pas au nord de la Statue de Zuiko. Quel est son nom de PNJ dans le temps présent?", r: "ume", v:"70", url:"https://fr.wikipedia.org/wiki/Angelina_(salon_de_th%C3%A9)" },
	{ i: 13,q: "Louis Pasteur, aujourd'hui apothicaire dans l'étendue de Rhalgr, est soulagé: La guerre finie, il suppose qu'il ne devrait plus avoir besoin d'autant de médicaments. Quel est son nom de PNJ dans le temps présent? ", r: "oreLla", v:"70", url:"https://fr.wikipedia.org/wiki/Louis_Pasteur"  },
	{ i: 14,q: "Ptolémée Ier a entrepris la construction du Phare d'Alexandrie mais aujourd'hui il espère seulement rallumer la flamme d'espoir du Phare de Sirius, quel est son nom de PNJ dans le temps présent?", r: "davYd", v:"70", url:"https://fr.wikipedia.org/wiki/Phare_d%27Alexandrie" },
	{ i: 15,q: "Eugène-François Vidocq, le roi des voleurs, le roi des policiers, officie aujourd'hui sur la place Tenkonto. Il vérifie s'il n'y a pas de hors-la-loi ou des fauteurs de troubles dans la foule. Quel est son nom de PNJ dans le temps présent?", r: "kyuSen", v:"70", url:"https://fr.wikipedia.org/wiki/Eug%C3%A8ne-Fran%C3%A7ois_Vidocq" },
	{ i: 16,q: "Blaise Pascal, l'inventeur de la première machine à calculer, a aujourd'hui bien du mal à compter les arrivages à la Gare de Roncenoire. Il y a tellement de caisses qui arrivent tous les jours, qu'il en perd le compte. Quel est son nom de PNJ dans le temps présent?", r: "zeZeda", v:"70", url:"https://fr.wikipedia.org/wiki/Blaise_Pascal" },
	{ i: 17,q: "Fra Mauro était un grand cartographe. Basé aujourd'hui à la Baie des Vèpres, il explore Eorzéa pour corriger et complétéer la carte de son grand-père. Quel est son nom de PNJ dans le temps présent", r: "nedricK ironheart", v:"70", url: "https://fr.wikipedia.org/wiki/Fra_Mauro" },
	{ i: 18,q: "Guy de la Brosse, le fondateur des Jardins du Roi qui deviendront le Museum national d'histoire naturelle, admire aujourd'hui l'éphémère beauté de fleurs du coté de Namai. C'est justement ce qui les rend si précieuses. Quel est son nom de PNJ dans le temps présent?", r: "ochiMi", v:"70", url:"https://fr.wikipedia.org/wiki/Guy_de_La_Brosse" },
	{ i: 19,q: "Vulcain était le dieu du feu, des volcans et des forgerons. Aujourd'hui, dans le camp de la ligue des cendres, il indique aux couards de Zanr'ak que 'des flammes, nos armes sont nées' et que 'Confier sa vie à son arme et confier son coeur à son dieu sont des choses différentes'. Quel est son nom de PNJ dans le temps présent?", r: "naruJj boh", v:"70", url:"https://fr.wikipedia.org/wiki/Vulcain_(mythologie)" },
	{ i: 20,q: "Le grand transformiste Leopoldo Fregoli qui changeait de tenues des dizaines de fois par spectacle, a perdu ses vêtements du coté des sources thermales de Bokaisen. Quel est son nom de PNJ dans le temps présent?", r: "kaWashige", v:"70", url:"https://fr.wikipedia.org/wiki/Leopoldo_Fregoli" }
];

// alza gamilza : goelier noscea occidentale, 24.9 26.6
